forge_support: false
player_limit: -1
permissions:
  default: null
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - cloudnet.command.cloudnet
  - cloudnet.syncproxy.fullljoin
  - cloudnet.syncproxy.maintenance
timeout: 30000
log_commands: true
online_mode: true
disabled_commands:
- bungee
servers:
  fallback:
    motd: ''
    address: localhost:16073
    restricted: false
listeners:
- query_port: 25577
  motd: ''
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - fallback
  default_server: fallback
  fallback_server: fallback
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 250
  tab_size: 60
  force_default_server: false
ip_forward: true
network_compression_threshold: 256
prevent_proxy_connections: false
groups:
  Devlayer:
  - admin
connection_throttle: 0
log_pings: true
